/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException {
       // TestCases tests = new TestCases(); // Initialize your test class
       // imageUrl imageurl = new imageUrl();
       // linkedInPost linkedin = new linkedInPost();
       // CountHyperLink count = new CountHyperLink();
       // Amazon links = new Amazon();
       // IMDBrating rating = new IMDBrating();
       // NestedFrames frames = new NestedFrames();
       // WindowHandle windows = new WindowHandle();

        //TODO: call your test case functions one after other here

        //tests.testCase01();
        //imageurl.testCase02();
        //linkedin.testCase03();
        //count.testCase04();
        //links.testCase05();
        //rating.testCase06();
        //frames.testCase07();
        //windows.testCase08();


        //END Tests
        //imageurl.endTest();
        //linkedin.endTest();
        //count.endTest();
        //links.endTest();
        //rating.endTest();
        //frames.endTest();
        //windows.endTest();

        //tests.endTest(); // End your test by clearning connections and closing browser
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
}
